version: "3.9"

services:
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  matchmaking:
    build:
      context: ./matchmaking
      dockerfile: Dockerfile
    environment:
      MM_HTTP_ADDR: ":8080"
      MM_REDIS_ADDR: "redis:6379"
      # заглушка; если координатор не нужен сейчас — оставьте пустым или удалите
      MM_COORDINATOR_URL: "http://localhost:8090"
      # при необходимости:
      # MM_MATCH_INTERVAL: "500ms"
      # MM_PAIR_RATING_DELTA: "150"
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy